using System.Drawing;
using System.Windows.Forms;

namespace AR1xController
{
    public delegate bool del_b_b(bool p0);
    public delegate bool del_b_b_b(bool p0, bool p1);
    public delegate bool del_b_cbo_i(ComboBox p0, int p1);
    public delegate bool del_b_channel_rate(ChannelData channel, RateData rate);
    public delegate void del_b_ctrl(bool p0, Control ctrl);
    public delegate bool del_b_i(int p0);
    public delegate bool del_b_i_i(int p0, int p1);
    public delegate bool del_b_s(string p0);
    public delegate uint del_b_u(uint p0, ushort p1);
    public delegate bool del_b_u_u_u(uint p0, uint p1, uint p2);
    public delegate bool del_b_u_u_u_us_us_us_b(uint p0, uint p1, uint p2, ushort p3, ushort p4, ushort p5, byte p6);
    public delegate bool del_b_v();
    public delegate int del_ChannelTune(sbyte channel, sbyte band, sbyte bandwidth);
    public delegate void del_ConnectAnalogPortsExtStart(int chain, int i_q, int domain, int from);
    public delegate double del_d_v();
    public delegate bool del_GetAnaPortsParams(ref int chain, ref int i_q, ref int domain);
    public delegate bool del_GetChannelTuneParams(ref int idx, ref int band, ref int bandwidth);
    public delegate bool del_GetExpectedPacketsVal(ref int num_expected_packets);
    public delegate bool del_GetPowerParams(ref int dbm, ref double target_power, ref int soc, ref int analog_setting, ref int ant_select, ref int channel_limits_disable, ref int fem_limits_disable, ref double post_dpd);
    public delegate bool del_GetPowerParams_api(ref int des_pwr, ref uint level_idx, ref uint freq_band, ref uint freq_prim_chan, ref int freq_2nd_chan, ref uint ant_select, ref uint non_srv, ref uint chan_limit, ref uint fem_limit, ref uint gain_calc_mode, ref uint analog_gain_idx, ref int post_dpd);
    public delegate AntMode del_GetSelectedAntMode();
    public delegate EnabledChain del_GetSelectedChains();
    public delegate ChannelData del_GetSelectedChannel();
    public delegate TxMode del_GetSelectedTxMode();
    public delegate TestPortLine del_GetSeletctedTestPortLine();
    public delegate bool del_GetTestSignalParams(ref int sweeps, ref int low, ref int high, ref int sawtooth, ref int step, ref int time, ref int cw1_I_select, ref int cw1_Q_select, ref int cw2_I_select, ref int cw2_Q_select, ref int mod_1, ref int mod_2, ref int mod_source, ref int manual_level, ref int mod1_I_select, ref int mod1_Q_select, ref int mod2_I_select, ref int mod2_Q_select, ref int ch1_source_mux1, ref int ch1_source_mux2, ref int ch2_source_mux1, ref int ch2_source_mux2, ref int sum1, ref int sum2);
    public delegate bool del_GetTxParams(ref int packet_mode, ref int p1, ref int preamble, ref double delay, ref int amount, ref int size, ref int rate, ref int const_data, ref int p8, ref int stbc, ref int scramble, ref int inc_mode, ref int seed);
    public delegate bool del_GetTxParams_api(ref uint delay, ref uint rate, ref uint size, ref uint mode, ref uint data_type, ref uint p5, ref string src_address, ref string dst_address, ref uint p8);
    public delegate int del_i_cbo(ComboBox p0);
    public delegate int del_i_i16a(short[] parr1);
    public delegate int del_i_objarr(object[] p0);
    public delegate int del_i_s(string p0);
    public delegate int del_i_u(uint p0);
    public delegate void del_v_v();
    public delegate void del_v_s_b(string p0, bool p1);
    public delegate void del_v_s(string p0);
    public delegate void del_v_ri_rb(ref int p0, ref bool p1);
    public delegate void del_v_objarr_i(object[] p0, int p1);
    public delegate void del_v_objarr(object[] p0);
    public delegate void del_v_i_s_b(uint p0, string p1, bool p2);
    public delegate void del_v_i_s(uint p0, string p1);
    public delegate void del_v_i_i_i(int op1, int op2, int op3);
    public delegate void del_v_i_i_b(int p0, int p1, bool p2);
    public delegate void del_v_i_i(uint p0, uint p1);
    public delegate void del_v_i_b(int p0, bool p1);
    public delegate void del_v_i(int p0);
    public delegate void del_v_c(Color p0);
    public delegate void del_v_b_sb_sb_sb_sb_(string p0);
    public delegate void del_v_b_b(bool p0, bool p1);
    public delegate void del_v_b(bool p0);
    public delegate void del_UpdateLuaKey(TsLuaKey key);
    public delegate void del_UpdateGuiPowerMode(PowerMode mode_num, bool ext);
    public delegate bool del_u_us_us_us_us_us_us_us_us_u(uint p0, ushort p1, ushort p2, ushort p3, ushort p4, ushort p5, ushort p6, ushort p7, ushort p8, uint p10);
    public delegate bool del_u_us_us_us_u(uint p0, ushort p1, ushort p2, ushort p3, ushort p4, uint p5);
    public delegate bool del_u_us_us_u_u(uint p0, ushort p1, ushort p2, uint p3, uint p4);
    public delegate bool del_u_us_us_c_us_c_u(uint p0, ushort p1, ushort p2, byte p3, ushort p4, byte p5, uint p6);
    public delegate bool del_u_us_us_c_su_u_u(uint p0, ushort p1, ushort p2, byte p3, int p4, uint p5, uint p6);
    public delegate bool del_u_us_us_c_c_us_us_c_c_u(uint p0, ushort p1, ushort p2, byte p3, byte p4, ushort p5, ushort p6, byte p7, byte p8, uint p10);
    public delegate bool del_u_us_us_b_u_u(uint p0, ushort p1, ushort p2, byte p3, uint p4, uint p5);
    public delegate bool del_u_u_uc(uint p0, uint p1, uint p2);
    public delegate bool del_u_u_u_us_us_us_us_us_us_us_u(uint p0, ushort p1, ushort p2, ushort p3, ushort p4, ushort p5, ushort p6, ushort p7, ushort p8, ushort p10, uint p11);
    public delegate bool del_u_u_u_us_us_us_us_us_us_u(uint p0, ushort p1, ushort p2, ushort p3, ushort p4, ushort p5, ushort p6, ushort p7, ushort p8, uint p10);
    public delegate bool del_u_u_u_u(uint p0, ushort p1, ushort p2, uint p3);
    public delegate bool del_u_u_u(uint p0, uint p1, ushort p2);
    public delegate bool del_u_u_s(uint p0, uint p1, short p2);
    public delegate bool del_u_u_c_u(uint p0, ushort p1, ushort p2, byte p3, uint p4);
    public delegate bool del_u_u_c_sc_us_u(uint p0, ushort p1, ushort p2, byte p3, sbyte p4, ushort p5, uint p6);
    public delegate bool del_u_u(uint p0, uint p1);
    public delegate void del_TestSignalExtStart(int sweeps, int low, int high, int sawtooth, int step, int time, int cw1_I_select, int cw1_Q_select, int cw2_I_select, int cw2_Q_select, int mod_1, int mod_2, int mod_source, int manual_level, int mod1_I_select, int mod1_Q_select, int mod2_I_select, int mod2_Q_select, int ch1_source_mux1, int ch1_source_mux2, int ch2_source_mux1, int ch2_source_mux2, int sum1, int sum2);
    public delegate void del_str(string text);
    public delegate void del_StartTxExtStart(int packet_mode, int p1, int preamble, double delay, int amount, int size, int rate, int const_data, int p8, int stbc, int scramble, int inc_mode, int seed);
    public delegate void del_StartTxApiExtStart(uint delay, uint rate, uint size, uint mode, uint data_type, uint p5, string src_address, string dst_address, uint p8);
    public delegate void del_SetPathInCombo(string path, ComboBox combo);
    public delegate void del_SetOutputPowerExtStart(int dbm, double target_power, int soc, int analog_setting, int ant_select, int channel_limits_disable, int fem_limits_disable, double post_dpd);
    public delegate string del_s_v();
    public delegate string del_s_txt(TextBox p0);
    public delegate void del_RunApiFunc(GuiOp op_id, object[] args);
    public delegate long del_ii_v();
    public delegate int del_i_v();
    public delegate int del_i_u_u_u(uint p0, uint p1, uint p2);

    public delegate bool delegate0100(uint p0, ushort p1, ushort p2, byte p3, uint p4, uint p5, uint p6);
    public delegate bool delegate0101(uint p0, ushort p1, ushort p2, byte p3, int p4, int p5, int p6, int p7, int p8, int p10, uint p11, uint p12);
    public delegate bool delegate0102(uint p0, ushort p1, ushort p2, byte p3, uint p4, uint p5, uint p6, uint p7, uint p8, uint p10, uint p11);
    public delegate bool delegate0107(uint p0, uint p1, uint p2, uint p3);
    public delegate bool delegate010f(uint p0, ushort p1, ushort p2, byte p3, uint p4, uint p5, uint p6, uint p7, uint p8, uint p10, uint p11, uint p12, uint p13, uint p14, uint p15, uint p16, uint p17);
    public delegate bool delegate0110(uint p0, ushort p1, ushort p2, short p3, short p4, short p5, short p6, short p7, short p8, short p10, short p11, short p12, short p13, uint p14);
    public delegate bool delegate0111(uint p0, string p1, string p2, string p3, string p4, string p5, string p6, string p7, string p8, string p10, string p11, string p12, string p13, string p14);
    public delegate bool delegate0112(uint p0, ushort p1, ushort p2, byte p3, uint p4, uint p5, uint p6, uint p7, uint p8, uint p10, uint p11, uint p12, uint p13, uint p17);
    public delegate bool delegate0114(uint p0, ushort p1, ushort p2, ushort p3, uint p4);
    public delegate void delegate011c(int p0, uint p1, int p2, int p3, uint p4);
    public delegate void delegate0125(int op1, int op2, int op3, int op4);
    public delegate void delegate0126(int op1, int op2, int op3, int op4, int op5, int op6);
    public delegate void delegate0e5(uint p0, string p1, string p2, string p3, string p4, string p5, string p6, string p7, string p8, string p9, string p10, string p11);
    public delegate void delegate0e6(byte p0, sbyte p1, sbyte p2, sbyte p3, sbyte p4, byte p5, byte p6, byte p7, byte p8, byte p9, byte p10, byte p11, byte p12, byte p13, byte p14, byte p15, byte p16, byte p17, byte p18, byte p19, sbyte p20, sbyte p21, sbyte p22, sbyte p23, byte p24, byte p25, byte p26, byte p27, byte p28, byte p29, byte p30, byte p31, byte p32, byte p33, byte p34, byte p35, byte p36, byte p37, byte p38, sbyte p40, sbyte p41, sbyte p42, sbyte p43, byte p44, byte p45, byte p46, byte p47, byte p48, byte p49, byte p50, byte p51, byte p52, byte p53, byte p54, byte p55, byte p56, byte p57, byte p58);
    public delegate void delegate0e7(byte p0, sbyte p1, sbyte p2, sbyte p3, sbyte p4, byte p5, byte p6, byte p7, byte p8, byte p9, byte p10, byte p11, byte p12, byte p13, byte p14, byte p15, byte p16, byte p17, byte p18, byte p19);
    public delegate int delegate0f1(uint p0, uint p1, string p2, uint p3);
    public delegate bool delegate0f9(ref int p0, ref uint p1, ref uint p2, ref uint p3);
    public delegate bool delegate0fc(uint p0, uint p1, uint p2, int p3, uint p4);
    public delegate bool delegate0ff(uint p0, int p1, int p2, int p3, int p4, int p5, int p6, int p7, int p8, int p10, int p11, int p12, int p13);
}
